version: 2.1
jobs:
  build:
    docker:
      - image: "thenerdybrewingco/build:dotnet3.1.100-bionic"
    working_directory: /overtheairbrew
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            withversion ./build.sh --buildNumber x.x.x
  push_release:
    working_directory: /thenerdybrewingco
    docker:
      - image: thenerdybrewingco/build:dotnet3.1.100-bionic
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: push tag
          command: |
            mkdir ./temp
            withversion echo "x.x.x" >> ./temp/buildno.txt
            withversion ghr -u overtheairbrew --repository ${CIRCLE_PROJECT_REPONAME} "vx.x.x" ./temp/

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: THENERDYBREWINGCO
      - push_release:
          context: THENERDYBREWINGCO
          requires:
            - build
          filters:
            tags:
              only: master
